#ifndef 	GENERAL_PIN_DEFINITIONS_H_
#define		GENERAL_PIN_DEFINITIONS_H_


//Select MCU
#define   MCU_STM32F100C4				//Target microcontroller

#ifdef		MCU_STM32F100C4
//-------------------------------PORTS------------------------------------
#define 	PORTA_PIN_0	 		A, 0,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA0							Alt: WKUP, USART2_CTS, ADC1_IN0, TIM2_CH1_ETR	
#define 	PORTA_PIN_1	 		A, 1,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA1							Alt: USART2_RTS, ADC1_IN1, TIM2_CH2
#define 	PORTA_PIN_2	 		A, 2,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA2							Alt: USART2_TX, ADC1_IN2, TIM2_CH3, TIM15_CH1
#define 	PORTA_PIN_3	 		A, 3,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA3							Alt: USART2_RX, ADC1_IN3, TIM2_CH4, TIM15_CH2
#define 	PORTA_PIN_4	 		A, 4,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA4							Alt: SPI1_NSS, USART2_CK, ADC1_IN4, DAC1_OUT
#define 	PORTA_PIN_5	 		A, 5,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA5							Alt: SPI1_SCK, ADC1_IN5, DAC2_OUT
#define 	PORTA_PIN_6	 		A, 6,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA6							Alt: SPI1_MISO, ADC1_IN6, TIM3_CH1				Remap: TIM1_BKIN, TIM16_CH1
#define 	PORTA_PIN_7	 		A, 7,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA7							Alt: SPI1_MOSI, ADC1_IN7, TIM3_CH2				Remap: TIM1_CH1N, TIM17_CH1
#define 	PORTA_PIN_8			A, 8,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA8							Alt: USART1_CK, MCO, TIM1_CH1
#define 	PORTA_PIN_9	 		A, 9,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA9							Alt: USART1_TX, TIM1_CH2, TIM15_BKIN 
#define 	PORTA_PIN_10	 	A, 10, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA10							Alt: USART1_RX, TIM1_CH3, TIM17_BKIN
#define 	PORTA_PIN_11	 	A, 11, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA11							Alt: USART1_CTS, TIM1_CH4							
#define 	PORTA_PIN_12		A, 12, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PA12							Alt: USART1_RTS, TIM1_ETR
#define 	PORTA_PIN_13 		A, 13, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// JTMS/SWDIO																						Remap: PA13
#define 	PORTA_PIN_14	 	A, 14, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// JTCK/SWCLK																						Remap: PA14
#define 	PORTA_PIN_15	 	A, 15, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// JTDI       																					Remap: PA15,SPI1_NSS,TIM2_CH1_ETR 

#define 	PORTB_PIN_0	 		B, 0,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB0							Alt: ADC1_IN8, TIM3_CH3							Remap: TIM1_CH2N	
#define 	PORTB_PIN_1	 		B, 1,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB1							Alt: ADC1_IN9, TIM3_CH4							Remap: TIM1_CH3N
#define 	PORTB_PIN_2	 		B, 2,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB2/BOOT1
#define 	PORTB_PIN_3	 		B, 3,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// JTDO																									Remap: PB3, TIM2_CH2, TRACE_SWO, SPI1_SCK
#define 	PORTB_PIN_4	 		B, 4,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// NJRST																								Remap: PB4, TIM3_CH1, SPI1_MISO
#define 	PORTB_PIN_5	 		B, 5,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB5							Alt: I2C1_SMBA, TIM16_BKIN 					Remap: TIM3_CH2,SPI1_MOSI
#define 	PORTB_PIN_6	 		B, 6,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB6							Alt: I2C1_SCL,TIM16_CH1N						Remap: USART1_TX
#define 	PORTB_PIN_7	 		B, 7,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB7							Alt: I2C1_SDA,TIM17_CH1N						Remap: USART1_RX
#define 	PORTB_PIN_8			B, 8,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB8							Alt: TIM16_CH1, CEC									Remap: I2C1_SCL
#define 	PORTB_PIN_9	 		B, 9,  LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB9							Alt: TIM17_CH1											Remap: I2C1_SDA
#define 	PORTB_PIN_10	 	B, 10, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB10																									Remap: TIM2_CH3, CEC		
#define 	PORTB_PIN_11	 	B, 11, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB11																									Remap: TIM2_CH4
#define 	PORTB_PIN_12		B, 12, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB12							Alt: TIM1_BKIN
#define 	PORTB_PIN_13 		B, 13, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB13							Alt: TIM1_CH1N
#define 	PORTB_PIN_14	 	B, 14, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB14							Alt: TIM1_CH2N											Remap: TIM15_CH1
#define 	PORTB_PIN_15	 	B, 15, LOW, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ		// PB15       			Alt: TIM1_CH3N											Remap: TIM15_CH2

//-------------------------------DAC------------------------------------
#define   DAC1						A, 4, LOW, ANALOG, INPUT_MODE
#define   DAC2						A, 5, LOW, ANALOG, INPUT_MODE

//-------------------------------ADC------------------------------------
#define   ADC1_IN0				A, 0, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN1				A, 1, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN2				A, 2, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN3				A, 3, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN4				A, 4, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN5				A, 5, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN6				A, 6, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN7				A, 7, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN8				B, 0, LOW, ANALOG, INPUT_MODE
#define   ADC1_IN9				B, 1, LOW, ANALOG, INPUT_MODE

//-------------------------------SPI------------------------------------
#define 	SPI1_NSS  		 	A, 4, HIGH, GENERAL_OUTPUT_PUSH_PULL, SPEED_10MHZ
#define 	SPI1_SCK	 			A, 5, HIGH, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_10MHZ
#define 	SPI1_MISO	 			A, 6, HIGH, INPUT_PULL_UP, INPUT_MODE
#define 	SPI1_MOSI	 			A, 7, HIGH, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_10MHZ

//-------------------------------I2C------------------------------------
#define 	I2C1_SDA	 			B, 7, HIGH, ALTERNATE_OUTPUT_OPEN_DRAIN, SPEED_2MHZ
#define 	I2C1_SCL  		 	B, 6, HIGH, ALTERNATE_OUTPUT_OPEN_DRAIN, SPEED_2MHZ

//------------------------------USART-----------------------------------
#define 	USART2_CTS	 		A, 0, LOW, INPUT_PULL_UP, INPUT_MODE
#define 	USART2_RTS  		A, 1, LOW, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_2MHZ
#define 	USART2_TX  		 	A, 2, HIGH, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_2MHZ
#define 	USART2_RX	 			A, 3, HIGH, INPUT_PULL_UP, INPUT_MODE
#define 	USART2_CK	 			A, 4, HIGH, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_2MHZ

#define 	USART1_CK	 			A, 8, HIGH, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_2MHZ
#define 	USART1_TX  		  A, 9, HIGH, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_2MHZ
#define 	USART1_RX	 			A, 10, HIGH, INPUT_PULL_UP, INPUT_MODE
#define 	USART1_CTS	 		A, 11, LOW, INPUT_PULL_UP, INPUT_MODE
#define 	USART1_RTS  		A, 12, LOW, ALTERNATE_OUTPUT_PUSH_PULL, SPEED_2MHZ

#endif	//MCU_STM32F100C4



#endif  //GENERAL_PIN_DEFINITIONS_H_
