
/*
Example:
#define PIN_DESCRIPTION 	C, 9, HIGH, GENERAL_OUTPUT_PUSH_PULL, SPEED_2MHZ

	1. Port name [A, B, C …]
	2. Pin number [0-15]
	3. Active lvl [HIGH, LOW]
	4. Mode
		ANALOG
		INPUT_FLOATING
		INPUT_PULL_DOWN
		INPUT_PULL_UP
		GENERAL_OUTPUT_OPEN_DRAIN
		GENERAL_OUTPUT_PUSH_PULL
		ALTERNATE_OUTPUT_OPEN_DRAIN
		ALTERNATE_OUTPUT_PUSH_PULL
	5. Max frequency
		INPUT_MODE					//Nessesary for input configurations
		SPEED_2MHZ
		SPEED_10MHZ
		SPEED_50MHZ

#define PIN_CONFIGURATION(PIN_DESCRIPTION) 
#define PIN_ON(PIN_DESCRIPTION)
#define PIN_OFF(PIN_DESCRIPTION)
*/

#ifndef MCU_GPIO_H_
#define MCU_GPIO_H_

//CNF[1:0] bits definitions

#define		ANALOG													0x00
#define		INPUT_FLOATING									0x01
#define		INPUT_PULL_DOWN									0x02
#define		INPUT_PULL_UP										0x02
#define		GENERAL_OUTPUT_OPEN_DRAIN				0x01
#define		GENERAL_OUTPUT_PUSH_PULL				0x00
#define		ALTERNATE_OUTPUT_OPEN_DRAIN			0x03
#define		ALTERNATE_OUTPUT_PUSH_PULL			0x02

//MODDE[1:0] bits definitions
#define		INPUT_MODE											0x00
#define		SPEED_2MHZ											0x02
#define		SPEED_10MHZ											0x01
#define		SPEED_50MHZ											0x03

//LEVEL

#define 	HIGH 			GPIO_BSRR_BS
#define		LOW				GPIO_BSRR_BR

#define GPIO_P0_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF0 | GPIO_CRL_MODE0);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 0; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;	
#define GPIO_P1_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF1 | GPIO_CRL_MODE1);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 4; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P2_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF2 | GPIO_CRL_MODE2);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 8; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P3_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF3 | GPIO_CRL_MODE3);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 12; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P4_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF4 | GPIO_CRL_MODE4);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 16; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P5_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF5 | GPIO_CRL_MODE5);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 20; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P6_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF6 | GPIO_CRL_MODE6);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 24; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P7_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRL 	&= ~(GPIO_CRL_CNF7 | GPIO_CRL_MODE7);	\
				GPIO##PORT->CRL		|= ((CNF_BITS << 2)|(MODE_BITS))<< 28; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;				

#define GPIO_P8_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF8 | GPIO_CRH_MODE8);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 0; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;	
#define GPIO_P9_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF9 | GPIO_CRH_MODE9);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 4; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P10_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF10 | GPIO_CRH_MODE10);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 8; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P11_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF11 | GPIO_CRH_MODE11);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 12; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P12_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF12 | GPIO_CRH_MODE12);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 16; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P13_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF13 | GPIO_CRH_MODE13);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 20; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P14_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF14 | GPIO_CRH_MODE14);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 24; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;
#define GPIO_P15_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO##PORT->CRH 	&= ~(GPIO_CRH_CNF15 | GPIO_CRH_MODE15);	\
				GPIO##PORT->CRH		|= ((CNF_BITS << 2)|(MODE_BITS))<< 28; 		\
				GPIO##PORT->BSRR 	|= LEVEL##PIN;		

#define GPIO_PIN_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS)				\
				GPIO_P##PIN##_CONFIGURATION(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS);
				
#define PIN_CONFIGURATION(PIN_DESCRIPTION)	GPIO_PIN_CONFIGURATION(PIN_DESCRIPTION);

#define GPIO_PIN_ON(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS) GPIO##PORT->BSRR 	|=GPIO_BSRR_BS##PIN;
#define PIN_ON(PIN_DESCRIPTION) 		GPIO_PIN_ON(PIN_DESCRIPTION);

#define GPIO_PIN_OFF(PORT,PIN,LEVEL,CNF_BITS,MODE_BITS) GPIO##PORT->BSRR 	|=GPIO_BSRR_BR##PIN;
#define PIN_OFF(PIN_DESCRIPTION) 		GPIO_PIN_OFF(PIN_DESCRIPTION);

#endif	//MCU_GPIO_H_
