/*
depending on microcontroller definitions for LCD16x2
*/

#define	 	LCD_16x2_DATA_PORT_DB4_PIN_MODE		 GPIOA->CRL &= ~GPIO_CRL_CNF6;
#define	 	LCD_16x2_DATA_PORT_DB4_PIN_SPEED	 GPIOA->CRL |= GPIO_CRL_MODE6_1;
#define	 	LCD_16x2_DATA_PORT_DB4_PIN_SET		 GPIOA->BSRR = GPIO_BSRR_BS6;
#define	 	LCD_16x2_DATA_PORT_DB4_PIN_RST		 GPIOA->BSRR = GPIO_BSRR_BR6;    

#define	 	LCD_16x2_DATA_PORT_DB5_PIN_MODE		 GPIOA->CRL &= ~GPIO_CRL_CNF5;
#define	 	LCD_16x2_DATA_PORT_DB5_PIN_SPEED	 GPIOA->CRL |= GPIO_CRL_MODE5_1;
#define	 	LCD_16x2_DATA_PORT_DB5_PIN_SET		 GPIOA->BSRR = GPIO_BSRR_BS5;
#define	 	LCD_16x2_DATA_PORT_DB5_PIN_RST		 GPIOA->BSRR = GPIO_BSRR_BR5;

#define	 	LCD_16x2_DATA_PORT_DB6_PIN_MODE		 GPIOB->CRH &= ~GPIO_CRH_CNF9;
#define	 	LCD_16x2_DATA_PORT_DB6_PIN_SPEED	 GPIOB->CRH |= GPIO_CRH_MODE9_1;
#define	 	LCD_16x2_DATA_PORT_DB6_PIN_SET		 GPIOB->BSRR = GPIO_BSRR_BS9;
#define	 	LCD_16x2_DATA_PORT_DB6_PIN_RST		 GPIOB->BSRR = GPIO_BSRR_BR9;

#define	 	LCD_16x2_DATA_PORT_DB7_PIN_MODE		 GPIOB->CRL &= ~GPIO_CRL_CNF0;
#define	 	LCD_16x2_DATA_PORT_DB7_PIN_SPEED	 GPIOB->CRL |= GPIO_CRL_MODE0_1;
#define	 	LCD_16x2_DATA_PORT_DB7_PIN_SET		 GPIOB->BSRR = GPIO_BSRR_BS0;
#define	 	LCD_16x2_DATA_PORT_DB7_PIN_RST		 GPIOB->BSRR = GPIO_BSRR_BR0;

#define	 	LCD_16x2_CTRL_RS_PIN_MODE		 	 GPIOB->CRH &= ~GPIO_CRH_CNF8;
#define	 	LCD_16x2_CTRL_RS_PIN_SPEED		 	 GPIOB->CRH |= GPIO_CRH_MODE8_1;
#define	 	LCD_16x2_CTRL_RS_PIN_SET		 	 GPIOB->BSRR = GPIO_BSRR_BS8;
#define	 	LCD_16x2_CTRL_RS_PIN_RST		 	 GPIOB->BSRR = GPIO_BSRR_BR8;

#define	 	LCD_16x2_CTRL_E_PIN_MODE		 	 GPIOA->CRL &= ~GPIO_CRL_CNF7;
#define	 	LCD_16x2_CTRL_E_PIN_SPEED		 	 GPIOA->CRL |= GPIO_CRL_MODE7_1;
#define	 	LCD_16x2_CTRL_E_PIN_SET		 	 	 GPIOA->BSRR = GPIO_BSRR_BS7;
#define	 	LCD_16x2_CTRL_E_PIN_RST		 	 	 GPIOA->BSRR = GPIO_BSRR_BR7;

#define	 	LCD_16x2_CTRL_RW_PIN_MODE		 	 GPIOB->CRL &= ~GPIO_CRL_CNF1;
#define	 	LCD_16x2_CTRL_RW_PIN_SPEED		 	 GPIOB->CRL |= GPIO_CRL_MODE1_1;
#define	 	LCD_16x2_CTRL_RW_PIN_SET		 	 GPIOB->BSRR = GPIO_BSRR_BS1;
#define	 	LCD_16x2_CTRL_RW_PIN_RST		 	 GPIOB->BSRR = GPIO_BSRR_BR1;
